// Generated by lsc from index.ts

datatype Option<T> = None | Some(value: T)

function StringIndexOf(s: string, sub: string): int
  ensures StringIndexOf(s, sub) == -1
       || (0 <= StringIndexOf(s, sub) <= |s| - |sub| && s[StringIndexOf(s, sub)..StringIndexOf(s, sub) + |sub|] == sub)
{
  StringIndexOfFrom(s, sub, 0)
}

function StringIndexOfFrom(s: string, sub: string, from: int): int
  ensures StringIndexOfFrom(s, sub, from) == -1
       || (0 <= StringIndexOfFrom(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFrom(s, sub, from)..StringIndexOfFrom(s, sub, from) + |sub|] == sub
           && StringIndexOfFrom(s, sub, from) >= from)
{
  StringIndexOfFromN(s, sub, if from < 0 then 0 else from)
}

function StringIndexOfFromN(s: string, sub: string, from: nat): int
  decreases |s| - from
  ensures StringIndexOfFromN(s, sub, from) == -1
       || (from <= StringIndexOfFromN(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFromN(s, sub, from)..StringIndexOfFromN(s, sub, from) + |sub|] == sub)
{
  if from + |sub| > |s| then -1
  else if s[from..from + |sub|] == sub then from as int
  else StringIndexOfFromN(s, sub, from + 1)
}

// Pointwise maximality: at any p before the returned index, no match exists.
lemma IndexOfMaxAt(s: string, sub: string, from: nat, p: int)
  requires |sub| > 0
  requires from <= p
  requires p + |sub| <= |s|
  requires StringIndexOfFromN(s, sub, from) == -1 || p < StringIndexOfFromN(s, sub, from)
  ensures s[p..p+|sub|] != sub
  decreases |s| - from
{
  if from + |sub| > |s| {
  } else if s[from..from + |sub|] == sub {
  } else if p == from {
  } else {
    IndexOfMaxAt(s, sub, from + 1, p);
  }
}

// Count of (overlapping) occurrences of `sub` in s[lo..hi]. Recurses on `hi`
// so the recursive case IS the extension-by-1 equation.
function CountAll(s: string, sub: string, lo: int, hi: int): nat
  requires 0 <= lo <= hi <= |s|
  requires |sub| > 0
  decreases hi - lo
{
  if hi - lo < |sub| then 0
  else (if s[hi - |sub|..hi] == sub then 1 else 0) + CountAll(s, sub, lo, hi - 1)
}

// Extending hi over a range with no new matches doesn't change the count.
lemma CountAllExtendNoMatch(s: string, sub: string, lo: int, hi: int, hi': int)
  requires 0 <= lo <= hi <= hi' <= |s|
  requires |sub| > 0
  requires forall k :: hi < k <= hi' && k >= lo + |sub| ==> s[k - |sub|..k] != sub
  ensures CountAll(s, sub, lo, hi') == CountAll(s, sub, lo, hi)
  decreases hi' - hi
{
  if hi' > hi {
    CountAllExtendNoMatch(s, sub, lo, hi, hi' - 1);
  }
}

// Extending hi to include exactly one new match at hi position `matchK` adds 1.
lemma CountAllExtendOneMatch(s: string, sub: string, lo: int, hi: int, matchK: int, hi': int)
  requires 0 <= lo <= hi < matchK <= hi' <= |s|
  requires |sub| > 0
  requires matchK >= lo + |sub|
  requires s[matchK - |sub|..matchK] == sub
  requires forall k :: hi < k <= hi' && k != matchK && k >= lo + |sub| ==> s[k - |sub|..k] != sub
  ensures CountAll(s, sub, lo, hi') == CountAll(s, sub, lo, hi) + 1
  decreases hi' - matchK
{
  if hi' > matchK {
    CountAllExtendOneMatch(s, sub, lo, hi, matchK, hi' - 1);
  } else {
    CountAllExtendNoMatch(s, sub, lo, hi, matchK - 1);
  }
}

// ====================================================================
// The two standalone lemmas that drive the maintenance proofs. They
// isolate the per-`k` forall reasoning into a small context (their own
// bodies) so the main method's verifier doesn't have to instantiate
// IndexOfMaxAt at every k under the method's full invariant context.
// ====================================================================

// "Extending CountAll's upper bound past the next match position adds exactly
// one." Used for both pushedCount maintenance (sub = a, p = the just-visited
// a-position) and poppedCount maintenance (sub = b, p = the just-popped
// b-position).
lemma CountAllExtendsByOne(s: string, sub: string, lo: int, p: int)
  requires |sub| > 0
  requires 0 <= lo <= p
  requires p + |sub| <= |s|
  requires s[p..p + |sub|] == sub
  ensures var nextFrom := StringIndexOfFromN(s, sub, p + 1);
          var hi_new := if nextFrom >= 0 then nextFrom + |sub| - 1 else |s|;
          var hi_old := p + |sub| - 1;
          0 <= hi_old <= hi_new <= |s|
       && CountAll(s, sub, lo, hi_new) == CountAll(s, sub, lo, hi_old) + 1
{
  var nextFrom := StringIndexOfFromN(s, sub, p + 1);
  var hi_old := p + |sub| - 1;
  var hi_new := if nextFrom >= 0 then nextFrom + |sub| - 1 else |s|;
  var matchK := p + |sub|;
  assert hi_old < matchK;
  // No matches in (matchK, hi_new]: position q = k - |sub| satisfies q > p,
  // and q < nextFrom (or nextFrom = -1), so IndexOfMaxAt applies.
  forall k | matchK < k <= hi_new && k >= lo + |sub|
    ensures s[k - |sub|..k] != sub
  {
    IndexOfMaxAt(s, sub, p + 1, k - |sub|);
  }
  CountAllExtendOneMatch(s, sub, lo, hi_old, matchK, hi_new);
}

// Shrink CountAll's lower bound by 1: the "lo position contributes 0 or 1"
// equation, dual to CountAll's hi-recursion. Symbolic: CountAll lo→lo+1
// removes exactly the start-position `lo` from consideration.
lemma CountAllShrinkLo(s: string, sub: string, lo: int, hi: int)
  requires |sub| > 0
  requires 0 <= lo
  requires lo + |sub| <= hi <= |s|
  ensures (if s[lo..lo + |sub|] == sub then 1 else 0)
       + CountAll(s, sub, lo + 1, hi) == CountAll(s, sub, lo, hi)
  decreases hi - lo
{
  if hi - (lo + 1) < |sub| {
    // hi == lo + |sub|: only one possible match position (lo itself).
    assert hi == lo + |sub|;
  } else {
    CountAllShrinkLo(s, sub, lo, hi - 1);
  }
}

// ====================================================================
// Branch-2 body-balance helper. Bundles ShrinkLo + NoOverlap + ExtendNoMatch
// for the result-conditional invariant. Factored as a standalone lemma so
// the main method's verifier sees a single call, not the assertion pile.
// ====================================================================
lemma BranchTwoBodyBalance(a: string, b: string, str: string,
                           b0: int, bi: int, hi_a: int, hi_b: int,
                           aiLowerBound: nat, ai: int,
                           pushedCount: nat, poppedCount: nat)
  requires |a| > 0 && |b| > 0
  requires 0 <= b0 && b0 + |a| <= |str| && str[b0..b0 + |a|] == a
  requires 0 <= bi && bi + |b| <= |str| && str[bi..bi + |b|] == b
  requires b0 <= bi
  requires hi_b == bi + |b| - 1
  requires hi_a == (if ai >= 0 then ai + |a| - 1 else |str|)
  requires 0 <= hi_a <= |str|
  requires aiLowerBound <= bi
  requires aiLowerBound <= |str|
  requires ai == StringIndexOfFromN(str, a, aiLowerBound)
  requires ai >= 0 ==> ai >= bi
  requires pushedCount == CountAll(str, a, b0, hi_a)
  requires poppedCount == CountAll(str, b, b0, hi_b)
  requires pushedCount == poppedCount + 1
  // Point-wise NoOverlap at b0 (caller derives from method's NoOverlap forall).
  requires str[b0..b0 + |b|] != b
  ensures b0 < bi
  ensures bi + |a| - 1 <= |str| ==>
            CountAll(str, a, b0 + 1, bi + |a| - 1)
            == CountAll(str, b, b0 + 1, bi + |b| - 1)
{
  // Strict ordering: caller's point-wise NoOverlap says str[b0..b0+|b|] != b.
  // Combined with str[bi..bi+|b|] == b and b0 <= bi: b0 < bi.
  assert str[b0..b0 + |b|] != b;
  // ShrinkLo for both sides: b0 IS an a-pos (contributes 1), NOT a b-pos (0).
  assert b0 + |a| <= hi_a;
  CountAllShrinkLo(str, a, b0, hi_a);
  CountAllShrinkLo(str, b, b0, hi_b);
  // Combined with pushedCount = poppedCount + 1:
  //   CountAll(str, a, b0+1, hi_a) == CountAll(str, b, b0+1, hi_b).
  assert CountAll(str, a, b0 + 1, hi_a) == CountAll(str, b, b0 + 1, hi_b);

  if bi + |a| - 1 <= |str| {
    // Shrink hi_a to bi+|a|-1 via ExtendNoMatch in reverse.
    // For k in (bi+|a|-1, hi_a] with k >= b0+1+|a|: position p = k-|a| is
    // in [bi, hi_a-|a|], p >= aiLowerBound (from invariant), so by
    // IndexOfMaxAt str[p..p+|a|] != a.
    forall k | bi + |a| - 1 < k <= hi_a && k >= (b0 + 1) + |a|
      ensures str[k - |a|..k] != a
    {
      IndexOfMaxAt(str, a, aiLowerBound, k - |a|);
    }
    CountAllExtendNoMatch(str, a, b0 + 1, bi + |a| - 1, hi_a);
  }
}

// Instantiate the NoOverlap precondition at a single position.
// Takes the point-wise NoOverlap disjunction as a precondition; callers
// derive it from the method's forall via an explicit assert (which gives
// the verifier a concrete trigger). Avoids passing the unconstrained forall
// across the lemma boundary, where its no-trigger shape causes brittle
// instantiation under isolate_assertions.
lemma NoOverlapAtAPos(a: string, b: string, s: string, p: int)
  requires |a| > 0 && |b| > 0
  requires 0 <= p && p + |a| <= |s| && p + |b| <= |s|
  requires s[p..p + |a|] == a
  requires s[p..p + |a|] != a || s[p..p + |b|] != b
  ensures s[p..p + |b|] != b
{ }

// "When p has no sub-start, CountAll(s, sub, p, hi_b) == 0 where hi_b extends
// up to the next sub-position via indexOf." Takes the point-wise no-overlap
// fact as a precondition (caller instantiates NoOverlap separately) — avoids
// having to unify universal-quantifier preconditions across method boundaries.
lemma CountAllZeroFromOtherStart(s: string, sub: string, p: int, from: nat,
                                 theIndex: int, hi_b: int)
  requires |sub| > 0
  requires 0 <= p
  requires from == p + 1
  requires theIndex == StringIndexOfFromN(s, sub, from)
  requires hi_b == (if theIndex >= 0 then theIndex + |sub| - 1 else |s|)
  requires p <= hi_b <= |s|
  // Point-wise no-overlap: sub doesn't start at p (or doesn't fit).
  requires p + |sub| > |s| || s[p..p + |sub|] != sub
  ensures CountAll(s, sub, p, hi_b) == 0
{
  forall k | p < k <= hi_b && k >= p + |sub|
    ensures s[k - |sub|..k] != sub
  {
    if k != p + |sub| {
      IndexOfMaxAt(s, sub, from, k - |sub|);
    }
  }
  CountAllExtendNoMatch(s, sub, p, p, hi_b);
}

// ====================================================================
// Functional reference: pure recursive rewrite of the imperative `range`
// loop. Used as the SPEC for behavioral-equivalence verification — the
// imperative method's ensures says `res == range_spec(a, b, str)`. This
// sidesteps the per-stack-frame CountAll-based fallback proof (which hits
// Z3 resource walls) by reducing correctness to "the algorithm computes
// this function" — a simulation invariant, not a per-frame counting argument.
// ====================================================================
function range_spec_loop(a: string, b: string, str: string,
                          i: int, ai: int, bi: int,
                          begs: seq<int>, left: int, right: Option<int>,
                          result: Option<seq<int>>): Option<seq<int>>
  requires |a| > 0 && |b| > 0
  requires ai >= -1 && (ai >= 0 ==> ai + |a| <= |str|)
  requires bi >= -1 && (bi >= 0 ==> bi + |b| <= |str|)
  // Loop's "i == ai || i == bi" invariant — without this, the branch-3 case
  // (else branch) can't conclude i == bi to advance bi via StringIndexOfFrom.
  requires i < 0 || i == ai || i == bi
  decreases (if result.Some? then 0 else 1)
            + (if ai >= 0 then |str| - ai else 0)
            + (if bi >= 0 then |str| - bi else 0)
{
  if i < 0 || result.Some? then
    // Loop exit. Apply post-loop fallback.
    match result {
      case Some(_) => result
      case None =>
        match right {
          case Some(r) => if |begs| > 0 then Some([left, r]) else None
          case None => None
        }
    }
  else if i == ai then
    // Branch 1: push i, advance ai.
    var newAi := StringIndexOfFrom(str, a, i + 1);
    var newI := if (newAi < bi) && (newAi >= 0) then newAi else bi;
    range_spec_loop(a, b, str, newI, newAi, bi, begs + [i], left, right, result)
  else if |begs| == 1 then
    // Branch 2: pop and set result.
    var newResult := Some([begs[|begs| - 1], bi]);
    var newBegs := begs[..|begs| - 1];
    range_spec_loop(a, b, str, i, ai, bi, newBegs, left, right, newResult)
  else
    // Branch 3: pop (if non-empty), maybe update left/right, advance bi.
    var beg := if |begs| > 0 then Some(begs[|begs| - 1]) else None;
    var newBegs := if |begs| > 0 then begs[..|begs| - 1] else begs;
    var (newLeft, newRight) := match beg {
      case Some(v) => if v < left then (v, Some(bi)) else (left, right)
      case None => (left, right)
    };
    var newBi := StringIndexOfFrom(str, b, i + 1);
    var newI := if (ai < newBi) && (ai >= 0) then ai else newBi;
    range_spec_loop(a, b, str, newI, ai, newBi, newBegs, newLeft, newRight, result)
}

function range_spec(a: string, b: string, str: string): Option<seq<int>>
  requires |a| > 0 && |b| > 0
{
  var ai := StringIndexOf(str, a);
  var bi := StringIndexOfFrom(str, b, ai + 1);
  if ai >= 0 && bi > 0 then
    if a == b then Some([ai, bi])
    else range_spec_loop(a, b, str, ai, ai, bi, [], |str|, None, None)
  else None
}

method range(a: string, b: string, str: string) returns (res: Option<seq<int>>)
  requires (|a| > 0)
  requires (|b| > 0)
  requires forall p: nat :: (((p + |a|) <= |str|) ==> ((p + |b|) <= |str|) ==> ((str[p..(p + |a|)] != a) || (str[p..(p + |b|)] != b)))
  ensures (match res { case Some(i_result_val) => (|i_result_val| == 2) case None => true })
  ensures (match res { case Some(i_result_val) => ((i_result_val[0] >= 0) && ((i_result_val[0] + |a|) <= |str|)) case None => true })
  ensures (match res { case Some(i_result_val) => ((i_result_val[1] >= 0) && ((i_result_val[1] + |b|) <= |str|)) case None => true })
  ensures (match res { case Some(i_result_val) => (i_result_val[0] <= i_result_val[1]) case None => true })
  ensures (match res { case Some(i_result_val) => (str[i_result_val[0]..(i_result_val[0] + |a|)] == a) case None => true })
  ensures (match res { case Some(i_result_val) => (str[i_result_val[1]..(i_result_val[1] + |b|)] == b) case None => true })
  // ---- UNIVERSAL refinement ensures: imperative method computes the spec. ----
  ensures res == range_spec(a, b, str)
{
  var begs: seq<int> := [];
  var beg := None;
  var left := 0;
  var right := None;
  var result := None;
  var ai := StringIndexOf(str, a);
  var bi := StringIndexOfFrom(str, b, (ai + 1));
  var i := ai;
  if ((ai >= 0) && (bi > 0)) {
    if (a == b) {
      return Some([ai, bi]);
    }
    begs := [];
    left := |str|;
    ghost var pushedCount: nat := 0;
    ghost var poppedCount: nat := 0;
    ghost var aiLowerBound: nat := 0;
    ghost var biLowerBound: nat := ai + 1;
    // Initial loop state (for refinement invariant). Stays constant.
    ghost var initAi := ai;
    ghost var initBi := bi;
    ghost var specFinal := range_spec_loop(a, b, str, ai, ai, bi, [], |str|, None, None);
    while ((i >= 0) && (match result { case Some(i_value) => false case None => true }))
      invariant ((ai == -1) || (((ai >= 0) && ((ai + |a|) <= |str|)) && (str[ai..(ai + |a|)] == a)))
      invariant ((bi == -1) || (((bi >= 0) && ((bi + |b|) <= |str|)) && (str[bi..(bi + |b|)] == b)))
      invariant ((ai == -1) || (ai >= i))
      invariant ((bi == -1) || (bi >= i))
      // Proof additions (Phase 1 + ordering):
      invariant match result {
        case Some(v) => |v| == 2 && 0 <= v[0] && v[0] + |a| <= |str|
                                 && 0 <= v[1] && v[1] + |b| <= |str|
                                 && v[0] <= v[1]
                                 && str[v[0]..v[0] + |a|] == a
                                 && str[v[1]..v[1] + |b|] == b
        case None => true
      }
      invariant match right {
        case Some(r) => 0 <= r && r + |b| <= |str| && str[r..r + |b|] == b
                     && 0 <= left && left + |a| <= |str| && str[left..left + |a|] == a
                     && left <= r
        case None => true
      }
      invariant forall j :: 0 <= j < |begs| ==>
                 0 <= begs[j] && begs[j] + |a| <= |str|
                 && str[begs[j]..begs[j] + |a|] == a
      // Ordering invariant: every pushed entry is at-or-before current scan
      // position, with a disjunct for the terminal state where the loop is
      // about to exit with leftover entries — those get drained by the
      // post-loop fallback that reads `left`/`right`. (Strict `<` would not
      // hold in general — counterexample: `range("ab", "a", "aab")` returns
      // [1, 1] via the fallback, because position 1 matches both `a` (str[1..3]
      // == "ab") and `b` (str[1..2] == "a").)
      invariant i == -1 || forall j :: 0 <= j < |begs| ==> begs[j] <= i
      invariant i == ai || i == bi
      // Algorithmic accounting: stack depth equals net pushes minus pops.
      // Foundation for any future Dyck-balanced argument — ties the current
      // state of `begs` to a count of branch-1 / branch-2 / branch-3 events.
      invariant |begs| == pushedCount - poppedCount
      // Lower-bound tracking: bi/ai are the result of indexOf with these `from`
      // values. Combined with the loop-entry pin, lets us deduce biLowerBound
      // == i_old + 1 at iter 1 (needed for IndexOfMaxAt application).
      invariant ai == StringIndexOfFromN(str, a, aiLowerBound)
      invariant bi == StringIndexOfFromN(str, b, biLowerBound)
      invariant aiLowerBound <= |str|
      invariant biLowerBound <= |str|
      // Loop-entry pin: iter 1 is the only iter with |begs| == 0 && result.None.
      // Pins all counters/bounds to their initial values, so we can transition
      // cleanly from "vacuous invariant" to "established invariant" on iter 1.
      invariant |begs| == 0 && result.None? ==> pushedCount == 0
                                             && poppedCount == 0
                                             && aiLowerBound == 0
                                             && biLowerBound == ai + 1
      // Helper invariants chaining begs[0] to ai/bi for CountAll's precondition.
      invariant |begs| > 0 && ai >= 0 ==> begs[0] <= ai
      invariant |begs| > 0 && bi >= 0 ==> begs[0] <= bi
      // aiLowerBound = (last push position) + 1. The last push happened with
      // i = ai <= bi (i is min when both >= 0), and by NoOverlap last push != bi,
      // so last push < bi, hence aiLowerBound <= bi. Needed at branch 2 to apply
      // IndexOfMaxAt at positions p >= bi.
      invariant |begs| > 0 && bi >= 0 ==> aiLowerBound <= bi
      // ---- Headline Phase 2 invariants: Dyck-balanced foundation. ----
      invariant |begs| > 0 ==> pushedCount == CountAll(str, a, begs[0],
                                if ai >= 0 then ai + |a| - 1 else |str|)
      invariant |begs| > 0 ==> poppedCount == CountAll(str, b, begs[0],
                                if bi >= 0 then bi + |b| - 1 else |str|)
      // result.Some? only via branch-2, which pops |begs| from 1 to 0.
      // Needed by the post-loop fallback bridge: lets Dafny case-split on
      // (result.Some, |begs|=0) — the case where the fallback's overwrite
      // condition (|begs| > 0) doesn't fire and result stays unchanged.
      invariant result.Some? ==> |begs| == 0
      // ---- Phase 2 UNIVERSAL: refinement against the functional spec. ----
      // Each loop iter corresponds to one recursive case of range_spec_loop;
      // the imperative state at iter-top always satisfies spec_loop(current)
      // == spec_loop(initial). At loop exit, spec_loop's "loop exit" branch
      // applies the post-loop fallback, matching the imperative's behavior.
      // Result: res == range_spec(a, b, str) — universal behavioral equivalence.
      invariant range_spec_loop(a, b, str, i, ai, bi, begs, left, right, result)
                == specFinal
      decreases (((match result { case Some(i_result_val) => 0 case None => 1 }) + (if (ai >= 0) then (|str| - ai) else 0)) + (if (bi >= 0) then (|str| - bi) else 0))
    {
      if (i == ai) {
        ghost var i_old := i;
        ghost var b0_old := if |begs| > 0 then begs[0] else i;
        ghost var preEmpty := |begs| == 0;
        // Pre-body i_old IS an a-position (branch 1 fires when i_old == ai).
        assert str[i_old..i_old + |a|] == a;
        assert i_old + |a| <= |str|;
        begs := (begs + [i]);
        pushedCount := pushedCount + 1;
        ai := StringIndexOfFrom(str, a, (i + 1));
        aiLowerBound := i + 1;
        assert ai == StringIndexOfFromN(str, a, i_old + 1);
        assert begs[0] == b0_old;
        // pushedCount maintenance via single lemma call (no inline forall).
        CountAllExtendsByOne(str, a, b0_old, i_old);
        // For iter 1 (preEmpty), also establish poppedCount = 0 invariant.
        if preEmpty {
          assert biLowerBound == i_old + 1;
          assert str[i_old..i_old + |a|] == a;
          assert i_old + |a| <= |str|;
          ghost var hi_b := if bi >= 0 then bi + |b| - 1 else |str|;
          if i_old + |b| <= |str| {
            // Instantiate the method's NoOverlap forall at q = i_old. The
            // explicit assert pins the trigger; without it Dafny's auto trigger
            // selection misses the instantiation under isolate_assertions.
            assert str[i_old..i_old + |a|] != a || str[i_old..i_old + |b|] != b;
            NoOverlapAtAPos(a, b, str, i_old);
          }
          CountAllZeroFromOtherStart(str, b, i_old, biLowerBound, bi, hi_b);
        }
      } else if (|begs| == 1) {
        // Branch 2: i === bi (since i != ai and i is one of ai/bi). bi is a
        // valid b-position. The popped element is at index |begs|-1 == 0; the
        // begs invariant gives us its a-position validity.
        assert i == bi;
        assert bi >= 0 && bi + |b| <= |str| && str[bi..bi + |b|] == b;
        assert |begs| > 0;
        assert 0 <= begs[0] && begs[0] + |a| <= |str| && str[begs[0]..begs[0] + |a|] == a;
        var r := (if (|begs| > 0) then Some(begs[(|begs| - 1)]) else None);
        begs := (if (|begs| > 0) then begs[0..(|begs| - 1)] else begs);
        poppedCount := poppedCount + 1;
        match r {
          case Some(i_r_val) =>
            result := Some([i_r_val, bi]);
          case None =>

        }
      } else {
        // Branch 3: i === bi (since i != ai). Pop, advance bi.
        ghost var bi_old := bi;
        ghost var i_old := i;
        ghost var b0_old := if |begs| > 0 then begs[0] else 0;
        // i_old IS a b-position (branch 3 fires when i != ai, so i == bi).
        assert i_old == bi_old;
        assert bi_old >= 0;
        assert str[bi_old..bi_old + |b|] == b;
        assert bi_old + |b| <= |str|;
        beg := (if (|begs| > 0) then Some(begs[(|begs| - 1)]) else None);
        ghost var hadElem := |begs| > 0;
        begs := (if (|begs| > 0) then begs[0..(|begs| - 1)] else begs);
        if hadElem { poppedCount := poppedCount + 1; }
        match beg {
          case Some(i_beg_val) =>
            if (i_beg_val < left) {
              left := i_beg_val;
              right := Some(bi);
            }
          case None =>

        }
        bi := StringIndexOfFrom(str, b, (i + 1));
        biLowerBound := i + 1;
        // poppedCount maintenance when |begs| stays > 0 (pre-pop |begs| >= 2).
        if |begs| > 0 {
          assert begs[0] == b0_old;
          assert bi == StringIndexOfFromN(str, b, bi_old + 1);
          CountAllExtendsByOne(str, b, b0_old, bi_old);
        }
      }
      i := (if ((ai < bi) && (ai >= 0)) then ai else bi);
    }
    // Pre-fallback bridge: spec_loop at the loop-exit branch returns the
    // value the fallback would compute. Capture and bridge.
    ghost var preFallbackResult := result;
    assert range_spec_loop(a, b, str, i, ai, bi, begs, left, right, preFallbackResult)
           == specFinal;
    match right {
      case Some(i_right_val) =>
        if (|begs| > 0) {
          result := Some([left, i_right_val]);
        }
      case None =>

    }
    // Post-fallback: by case analysis, result == spec_loop(pre-state).
    //   result.Some pre ⇒ |begs|=0 (only branch-2 sets result; pops to 0) ⇒
    //     fallback overwrite doesn't fire ⇒ result unchanged ⇒
    //     spec_loop(pre) = result (Some case) = current result.
    //   result.None pre + right.None ⇒ no fallback ⇒ result = None ⇒
    //     spec_loop(pre) = None = current result.
    //   result.None pre + right.Some && |begs|>0 ⇒ result := Some([left, r]) ⇒
    //     spec_loop(pre) = Some([left, r]) = current result.
    //   result.None pre + right.Some && |begs|=0 ⇒ no overwrite ⇒
    //     spec_loop(pre) = None = current result (still None).
    assert result == range_spec_loop(a, b, str, i, ai, bi, begs, left, right, preFallbackResult);
    assert result == specFinal;
    assert result == range_spec(a, b, str);
  }
  // Path 1 (outer if false): result = None, range_spec(a, b, str) unfolds to None
  // because !(initAi >= 0 && initBi > 0). Dafny derives by function unfolding.
  return result;
}
