// Generated by lsc from index.ts

datatype Option<T> = None | Some(value: T)

function StringIndexOf(s: string, sub: string): int
  ensures StringIndexOf(s, sub) == -1
       || (0 <= StringIndexOf(s, sub) <= |s| - |sub| && s[StringIndexOf(s, sub)..StringIndexOf(s, sub) + |sub|] == sub)
{
  StringIndexOfFrom(s, sub, 0)
}

function StringIndexOfFrom(s: string, sub: string, from: int): int
  ensures StringIndexOfFrom(s, sub, from) == -1
       || (0 <= StringIndexOfFrom(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFrom(s, sub, from)..StringIndexOfFrom(s, sub, from) + |sub|] == sub
           && StringIndexOfFrom(s, sub, from) >= from)
{
  StringIndexOfFromN(s, sub, if from < 0 then 0 else from)
}

function StringIndexOfFromN(s: string, sub: string, from: nat): int
  decreases |s| - from
  ensures StringIndexOfFromN(s, sub, from) == -1
       || (from <= StringIndexOfFromN(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFromN(s, sub, from)..StringIndexOfFromN(s, sub, from) + |sub|] == sub)
{
  if from + |sub| > |s| then -1
  else if s[from..from + |sub|] == sub then from as int
  else StringIndexOfFromN(s, sub, from + 1)
}

method range(a: string, b: string, str: string) returns (res: Option<seq<int>>)
  requires (|a| > 0)
  requires (|b| > 0)
  ensures (match res { case Some(i_result_val) => (|i_result_val| == 2) case None => true })
  ensures (match res { case Some(i_result_val) => ((i_result_val[0] >= 0) && ((i_result_val[0] + |a|) <= |str|)) case None => true })
  ensures (match res { case Some(i_result_val) => ((i_result_val[1] >= 0) && ((i_result_val[1] + |b|) <= |str|)) case None => true })
  ensures (match res { case Some(i_result_val) => (i_result_val[0] <= i_result_val[1]) case None => true })
  ensures (match res { case Some(i_result_val) => (str[i_result_val[0]..(i_result_val[0] + |a|)] == a) case None => true })
  ensures (match res { case Some(i_result_val) => (str[i_result_val[1]..(i_result_val[1] + |b|)] == b) case None => true })
{
  var begs: seq<int> := [];
  var beg := None;
  var left := 0;
  var right := None;
  var result := None;
  var ai := StringIndexOf(str, a);
  var bi := StringIndexOfFrom(str, b, (ai + 1));
  var i := ai;
  if ((ai >= 0) && (bi > 0)) {
    if (a == b) {
      return Some([ai, bi]);
    }
    begs := [];
    left := |str|;
    ghost var pushedCount: nat := 0;
    ghost var poppedCount: nat := 0;
    while ((i >= 0) && (match result { case Some(i_value) => false case None => true }))
      invariant ((ai == -1) || (((ai >= 0) && ((ai + |a|) <= |str|)) && (str[ai..(ai + |a|)] == a)))
      invariant ((bi == -1) || (((bi >= 0) && ((bi + |b|) <= |str|)) && (str[bi..(bi + |b|)] == b)))
      invariant ((ai == -1) || (ai >= i))
      invariant ((bi == -1) || (bi >= i))
      // Proof additions (Phase 1 + ordering):
      invariant match result {
        case Some(v) => |v| == 2 && 0 <= v[0] && v[0] + |a| <= |str|
                                 && 0 <= v[1] && v[1] + |b| <= |str|
                                 && v[0] <= v[1]
                                 && str[v[0]..v[0] + |a|] == a
                                 && str[v[1]..v[1] + |b|] == b
        case None => true
      }
      invariant match right {
        case Some(r) => 0 <= r && r + |b| <= |str| && str[r..r + |b|] == b
                     && 0 <= left && left + |a| <= |str| && str[left..left + |a|] == a
                     && left <= r
        case None => true
      }
      invariant forall j :: 0 <= j < |begs| ==>
                 0 <= begs[j] && begs[j] + |a| <= |str|
                 && str[begs[j]..begs[j] + |a|] == a
      // Ordering: every pushed entry is <= current scan position, unless the
      // loop is about to exit (i == -1) with leftover entries — those get
      // drained by the post-loop fallback that reads `left`/`right`.
      // (Strict `<` would not hold in general — counterexample: `range("ab",
      // "a", "aab")` returns [1, 1] via the fallback, because position 1
      // matches both `a` (str[1..3] == "ab") and `b` (str[1..2] == "a").)
      invariant i == -1 || forall j :: 0 <= j < |begs| ==> begs[j] <= i
      invariant i == ai || i == bi
      // Algorithmic accounting: stack depth equals net pushes minus pops.
      // This is the foundation invariant for any Dyck-balanced argument —
      // it ties the current state of `begs` to a count of branch-1 / branch-2
      // / branch-3 events the loop has performed.
      invariant |begs| == pushedCount - poppedCount
      decreases (((match result { case Some(i_result_val) => 0 case None => 1 }) + (if (ai >= 0) then (|str| - ai) else 0)) + (if (bi >= 0) then (|str| - bi) else 0))
    {
      if (i == ai) {
        begs := (begs + [i]);
        pushedCount := pushedCount + 1;
        ai := StringIndexOfFrom(str, a, (i + 1));
      } else if (|begs| == 1) {
        // Branch 2: i === bi (since i !== ai and i is one of ai/bi). bi is a
        // valid b-position. The popped element is at index |begs|-1 == 0; the
        // begs invariant gives us its a-position validity.
        assert i == bi;
        assert bi >= 0 && bi + |b| <= |str| && str[bi..bi + |b|] == b;
        assert |begs| > 0;
        assert 0 <= begs[0] && begs[0] + |a| <= |str| && str[begs[0]..begs[0] + |a|] == a;
        var r := (if (|begs| > 0) then Some(begs[(|begs| - 1)]) else None);
        begs := (if (|begs| > 0) then begs[0..(|begs| - 1)] else begs);
        poppedCount := poppedCount + 1;
        match r {
          case Some(i_r_val) =>
            result := Some([i_r_val, bi]);
          case None =>

        }
      } else {
        beg := (if (|begs| > 0) then Some(begs[(|begs| - 1)]) else None);
        ghost var hadElem := |begs| > 0;
        begs := (if (|begs| > 0) then begs[0..(|begs| - 1)] else begs);
        if hadElem { poppedCount := poppedCount + 1; }
        match beg {
          case Some(i_beg_val) =>
            if (i_beg_val < left) {
              left := i_beg_val;
              right := Some(bi);
            }
          case None =>

        }
        bi := StringIndexOfFrom(str, b, (i + 1));
      }
      i := (if ((ai < bi) && (ai >= 0)) then ai else bi);
    }
    match right {
      case Some(i_right_val) =>
        if (|begs| > 0) {
          result := Some([left, i_right_val]);
        }
      case None =>

    }
  }
  return result;
}
